"""empty message

Revision ID: 98e828776157
Revises: 
Create Date: 2020-02-29 13:57:56.150946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e828776157'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'password')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
